"""initial_schema_phase1

Revision ID: 14c42e5d4b45
Revises: 
Create Date: 2025-11-04 00:04:04.504444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '14c42e5d4b45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Создаём расширение pgvector (только для PostgreSQL)
    # ПРИМЕЧАНИЕ: pgvector должен быть предварительно установлен в системе:
    # В Docker: apt-get install postgresql-16-pgvector
    # Если расширение недоступно, миграция продолжится без него
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        try:
            op.execute('CREATE EXTENSION IF NOT EXISTS vector')
        except Exception as e:
            import warnings
            warnings.warn(f"pgvector extension not available: {e}. Vector columns will use text type.")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_user_updated', 'ai_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=63), nullable=False),
    sa.Column('key_ciphertext', sa.Text(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_user_provider', 'api_keys', ['user_id', 'provider'], unique=False)
    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('component', sa.String(length=127), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_logs_level_created', 'app_logs', ['level', 'created_at'], unique=False)
    op.create_index('idx_app_logs_user_created', 'app_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_app_logs_created_at'), 'app_logs', ['created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'parsed', 'indexed', 'error', name='document_status'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_owner_status', 'documents', ['owner_id', 'status'], unique=False)
    op.create_index('idx_documents_sha256', 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('job_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('index', 'ocr', 'embed', 'cleanup', name='job_type'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'error', name='job_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('locked_by', sa.String(length=63), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_queue_status_priority', 'job_queue', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('idx_job_queue_user', 'job_queue', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_history_user_created', 'search_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('user_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=127), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_models_user_active', 'user_models', ['user_id', 'is_active'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('chunk_idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_document', 'chunks', ['document_id', 'chunk_idx'], unique=False)
    op.create_index('idx_chunks_owner', 'chunks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_chunks_text_sha256'), 'chunks', ['text_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_text_sha256'), table_name='chunks')
    op.drop_index('idx_chunks_owner', table_name='chunks')
    op.drop_index('idx_chunks_document', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_messages_conversation', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('idx_user_models_user_active', table_name='user_models')
    op.drop_table('user_models')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index('idx_sessions_user_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_index('idx_search_history_user_created', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('idx_job_queue_user', table_name='job_queue')
    op.drop_index('idx_job_queue_status_priority', table_name='job_queue')
    op.drop_table('job_queue')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index('idx_documents_sha256', table_name='documents')
    op.drop_index('idx_documents_owner_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_app_logs_created_at'), table_name='app_logs')
    op.drop_index('idx_app_logs_user_created', table_name='app_logs')
    op.drop_index('idx_app_logs_level_created', table_name='app_logs')
    op.drop_table('app_logs')
    op.drop_index('idx_api_keys_user_provider', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('idx_conversations_user_updated', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
