"""add_prompts_table

Revision ID: 7a22d26c725f
Revises: 7949e1970345
Create Date: 2025-11-10 03:20:19.265815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a22d26c725f'
down_revision: Union[str, None] = '7949e1970345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('component', sa.String(length=127), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_logs_component', 'error_logs', ['component'], unique=False)
    op.create_index('idx_error_logs_type_created', 'error_logs', ['error_type', 'created_at'], unique=False)
    op.create_index('idx_error_logs_unresolved', 'error_logs', ['is_resolved', 'created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_table('http_request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_http_logs_path_created', 'http_request_logs', ['path', 'created_at'], unique=False)
    op.create_index('idx_http_logs_status', 'http_request_logs', ['response_status'], unique=False)
    op.create_index('idx_http_logs_user_created', 'http_request_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_http_request_logs_created_at'), 'http_request_logs', ['created_at'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompts_user', 'prompts', ['user_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(length=127), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Integer(), nullable=True),
    sa.Column('cost_rub', sa.Integer(), nullable=True),
    sa.Column('input_cost_usd', sa.Integer(), nullable=True),
    sa.Column('output_cost_usd', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_model_created', 'token_usage', ['model_id', 'created_at'], unique=False)
    op.create_index('idx_token_usage_user_created', 'token_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_created_at'), 'token_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_model_id'), 'token_usage', ['model_id'], unique=False)
    op.alter_column('ai_model_configs', 'price_input_per_1m',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'price_output_per_1m',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'price_per_1000_requests',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Integer(),
               existing_nullable=True)
    # Оставляем metadata как JSONB и search_vector как TSVECTOR с GIN индексом
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'last_folder',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_folder',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('sessions', 'is_active')
    # Оставляем metadata как JSONB и search_vector как TSVECTOR
    op.alter_column('ai_model_configs', 'price_per_1000_requests',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'price_output_per_1m',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('ai_model_configs', 'price_input_per_1m',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.drop_index(op.f('ix_token_usage_model_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_created_at'), table_name='token_usage')
    op.drop_index('idx_token_usage_user_created', table_name='token_usage')
    op.drop_index('idx_token_usage_model_created', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('idx_prompts_user', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_http_request_logs_created_at'), table_name='http_request_logs')
    op.drop_index('idx_http_logs_user_created', table_name='http_request_logs')
    op.drop_index('idx_http_logs_status', table_name='http_request_logs')
    op.drop_index('idx_http_logs_path_created', table_name='http_request_logs')
    op.drop_table('http_request_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index('idx_error_logs_unresolved', table_name='error_logs')
    op.drop_index('idx_error_logs_type_created', table_name='error_logs')
    op.drop_index('idx_error_logs_component', table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
